# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interpolate_map <- function(oldpos, oldmap, newmap) {
    .Call(`_mmconvert_interpolate_map`, oldpos, oldmap, newmap)
}

